// backend/supabase/functions/simulate/index.ts
import { createClient } from "npm:@supabase/supabase-js@2.38.0"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS, GET',
  'Access-Control-Allow-Credentials': 'true',
  'Vary': 'Origin'
}

const sleep = (ms: number) => new Promise((res) => setTimeout(res, ms))

// Fonction pour générer un maillage structuré simple (grille 3D)
function generateStructuredMesh(dimensions: [number, number, number], spacing: [number, number, number]) {
  const [nx, ny, nz] = dimensions;
  const [dx, dy, dz] = spacing;
  
  // Générer les points
  const points = [];
  const temperatureValues = [];
  
  for (let k = 0; k < nz; k++) {
    for (let j = 0; j < ny; j++) {
      for (let i = 0; i < nx; i++) {
        const x = i * dx;
        const y = j * dy;
        const z = k * dz;
        points.push(x, y, z);
        
        // Calculer une température basée sur la position (fonction gaussienne)
        const center = [nx*dx/2, ny*dy/2, nz*dz/2];
        const distance = Math.sqrt(
          Math.pow(x - center[0], 2) +
          Math.pow(y - center[1], 2) +
          Math.pow(z - center[2], 2)
        );
        
        // Température: 25°C à l'extérieur, 200°C au centre
        const temperature = 25 + (175 * Math.exp(-distance / (Math.max(nx*dx, ny*dy, nz*dz) / 3)));
        temperatureValues.push(temperature);
      }
    }
  }
  
  return { points, temperatureValues };
}

// Fonction pour générer un fichier VTK (format ASCII pour Structured Grid)
function generateVTKFile(config: any, temperatureData: number[]) {
  const { dimensions, spacing } = config;
  const [nx, ny, nz] = dimensions;
  const [dx, dy, dz] = spacing;
  
  let vtkContent = `# vtk DataFile Version 4.2
Generated by Industrial Simulation
ASCII
DATASET STRUCTURED_GRID
DIMENSIONS ${nx} ${ny} ${nz}
POINTS ${nx * ny * nz} float
`;

  // Générer les points
  for (let k = 0; k < nz; k++) {
    for (let j = 0; j < ny; j++) {
      for (let i = 0; i < nx; i++) {
        const x = i * dx;
        const y = j * dy;
        const z = k * dz;
        vtkContent += `${x} ${y} ${z}\n`;
      }
    }
  }

  // Ajouter les données scalaires (température)
  vtkContent += `
POINT_DATA ${nx * ny * nz}
SCALARS temperature float 1
LOOKUP_TABLE default
`;

  for (const temp of temperatureData) {
    vtkContent += `${temp}\n`;
  }

  return vtkContent;
}

Deno.serve(async (req: Request) => {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response(null, { 
      status: 204, 
      headers: corsHeaders 
    });
  }

  // Only allow POST
  if (req.method !== 'POST') {
    return new Response(
      JSON.stringify({ 
        success: false, 
        error: 'Method not allowed. Use POST.' 
      }), {
        status: 405,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );
  }

  let simulationId: string | undefined = undefined;

  try {
    // Validate authorization
    const authHeader = req.headers.get('Authorization');
    if (!authHeader?.startsWith('Bearer ')) {
      return new Response(
        JSON.stringify({ 
          success: false, 
          error: 'Missing or invalid Authorization header' 
        }), {
          status: 401,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        }
      );
    }

    const authToken = authHeader.replace(/^Bearer\s+/i, '');
    
    // Parse and validate request body
    let body: any;
    try {
      body = await req.json();
    } catch {
      return new Response(
        JSON.stringify({ 
          success: false, 
          error: 'Invalid JSON body' 
        }), {
          status: 400,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        }
      );
    }

    const { simulation_id: simId, config, user_id } = body;
    simulationId = simId;

    console.log(`[Simulate] Starting simulation ${simId} for user ${user_id}`);

    // Validate required fields
    if (!simId || !config || !user_id) {
      return new Response(
        JSON.stringify({ 
          success: false, 
          error: 'Missing required fields: simulation_id, config, user_id' 
        }), {
          status: 400,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        }
      );
    }

    // Initialize Supabase clients
    const SUPABASE_URL = Deno.env.get('SUPABASE_URL');
    const SUPABASE_ANON_KEY = Deno.env.get('SUPABASE_ANON_KEY');
    const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');

    if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
      throw new Error('Missing Supabase environment variables');
    }

    const supabaseServiceRoleClient = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

    // Verify simulation exists
    const { data: simulation, error: simError } = await supabaseServiceRoleClient
      .from('simulations')
      .select('id, user_id, status, geometry_config')
      .eq('id', simId)
      .eq('user_id', user_id)
      .single();

    if (simError || !simulation) {
      return new Response(
        JSON.stringify({ 
          success: false, 
          error: 'Simulation not found or unauthorized' 
        }), {
          status: 404,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        }
      );
    }

    // 1. Generate mesh and temperature data
    console.log(`[Simulate] Generating mesh for simulation ${simId}`);
    
    // Configuration du maillage basée sur la densité
    const meshDensity = config.mesh_density || 'medium';
    let dimensions: [number, number, number], spacing: [number, number, number];
    
    switch (meshDensity) {
      case 'low':
        dimensions = [20, 20, 20];
        spacing = [5, 5, 5];
        break;
      case 'high':
        dimensions = [50, 50, 50];
        spacing = [2, 2, 2];
        break;
      default: // medium
        dimensions = [30, 30, 30];
        spacing = [3.33, 3.33, 3.33];
    }

    // Générer les données du maillage
    const { points, temperatureValues } = generateStructuredMesh(dimensions, spacing);
    
    // Calculer les statistiques
    const maxTemp = Math.max(...temperatureValues);
    const minTemp = Math.min(...temperatureValues);
    const avgTemp = temperatureValues.reduce((a, b) => a + b, 0) / temperatureValues.length;
    
    // 2. Generate VTK file
    console.log(`[Simulate] Generating VTK file for ${dimensions[0]}x${dimensions[1]}x${dimensions[2]} grid`);
    const vtkContent = generateVTKFile({ dimensions, spacing }, temperatureValues);
    
    // 3. Upload VTK file to Supabase Storage
    const timestamp = Date.now();
    const fileName = `simulation_${simId}_${timestamp}.vtk`;
    const filePath = `${user_id}/${fileName}`;
    
    console.log(`[Simulate] Uploading VTK file to storage: ${filePath}`);
    
    const { data: uploadData, error: uploadError } = await supabaseServiceRoleClient
      .storage
      .from('simulation-files')
      .upload(filePath, vtkContent, {
        contentType: 'text/plain',
        upsert: false,
      });

    if (uploadError) {
      console.error(`[Simulate] Upload error: ${uploadError.message}`);
      throw new Error(`Failed to upload VTK file: ${uploadError.message}`);
    }

    // Get public URL
    const { data: urlData } = supabaseServiceRoleClient
      .storage
      .from('simulation-files')
      .getPublicUrl(filePath);

    const vtkFileUrl = urlData.publicUrl;
    console.log(`[Simulate] VTK file available at: ${vtkFileUrl}`);

    // 4. Simulate progress with realistic steps
    const simulationSteps = [
      { step: 'Initialisation', progress: 5 },
      { step: 'Génération du maillage', progress: 15 },
      { step: 'Définition des conditions limites', progress: 25 },
      { step: 'Résolution thermique', progress: 45 },
      { step: 'Convergence du solveur', progress: 65 },
      { step: 'Post-traitement', progress: 85 },
      { step: 'Génération des résultats', progress: 100 }
    ];

    for (const simStep of simulationSteps) {
      console.log(`[Simulate] ${simStep.step} - ${simStep.progress}%`);
      
      // Update simulation progress
      await supabaseServiceRoleClient
        .from('simulations')
        .update({ 
          progress: simStep.progress,
          updated_at: new Date().toISOString()
        })
        .eq('id', simId);
      
      // Simulate computation time based on mesh density
      const waitTime = meshDensity === 'high' ? 3000 : 
                      meshDensity === 'medium' ? 2000 : 1000;
      await sleep(waitTime);
    }

    // 5. Prepare simulation results
    const results = {
      vtk_file_url: vtkFileUrl,
      max_temperature: maxTemp,
      min_temperature: minTemp,
      average_temperature: avgTemp,
      computation_time: dimensions[0] * dimensions[1] * dimensions[2] * 0.01, // Simulated based on mesh size
      uncertainty_score: Math.random() * 0.15, // 0-15% uncertainty
      convergence_rate: 0.95 + Math.random() * 0.04, // 95-99%
      temperature_field: {
        values: temperatureValues,
        units: '°C',
        resolution: dimensions
      },
      mesh_points: dimensions[0] * dimensions[1] * dimensions[2],
      mesh_metadata: {
        vertices: dimensions[0] * dimensions[1] * dimensions[2],
        cells: (dimensions[0] - 1) * (dimensions[1] - 1) * (dimensions[2] - 1),
        type: 'structured',
        quality: {
          aspect_ratio: 1.0,
          skewness: 0.0,
          orthogonal_quality: 1.0
        }
      }
    };

    // 6. Save results to database
    console.log(`[Simulate] Saving results to database for ${simId}`);
    
    // Update simulation status
    const { error: updateError } = await supabaseServiceRoleClient
      .from('simulations')
      .update({ 
        status: 'completed', 
        progress: 100,
        completed_at: new Date().toISOString() 
      })
      .eq('id', simId);

    if (updateError) throw updateError;

    // Save results to simulation_results table
    const { error: resultsError } = await supabaseServiceRoleClient
      .from('simulation_results')
      .insert({ 
        simulation_id: simId,
        ...results,
        created_at: new Date().toISOString()
      });

    if (resultsError) throw resultsError;

    // Save mesh data
    const { error: meshError } = await supabaseServiceRoleClient
      .from('mesh_data')
      .insert({
        simulation_id: simId,
        file_name: fileName,
        file_url: vtkFileUrl,
        file_size: vtkContent.length,
        mesh_type: 'structured_grid',
        element_count: (dimensions[0] - 1) * (dimensions[1] - 1) * (dimensions[2] - 1),
        node_count: dimensions[0] * dimensions[1] * dimensions[2],
        quality_metric: 1.0,
        bounds: {
          x: [0, (dimensions[0] - 1) * spacing[0]],
          y: [0, (dimensions[1] - 1) * spacing[1]],
          z: [0, (dimensions[2] - 1) * spacing[2]]
        },
        created_at: new Date().toISOString()
      });

    if (meshError) console.warn(`[Simulate] Mesh data save warning: ${meshError.message}`);

    // Save visualization data
    const { error: vizError } = await supabaseServiceRoleClient
      .from('visualization_data')
      .insert({
        simulation_id: simId,
        vtk_file_url: vtkFileUrl,
        png_preview_url: null, // Will be generated by a separate process
        color_map: 'thermal',
        camera_angles: [
          { position: [100, 100, 100], focalPoint: [50, 50, 50], viewUp: [0, 0, 1] },
          { position: [0, 100, 50], focalPoint: [50, 50, 50], viewUp: [0, 0, 1] },
          { position: [100, 0, 50], focalPoint: [50, 50, 50], viewUp: [0, 0, 1] }
        ],
        created_at: new Date().toISOString()
      });

    if (vizError) console.warn(`[Simulate] Visualization data save warning: ${vizError.message}`);

    console.log(`[Simulate] Simulation ${simId} completed successfully`);

    return new Response(
      JSON.stringify({ 
        success: true, 
        simulation_id: simId, 
        status: 'completed', 
        results,
        message: 'Simulation completed successfully' 
      }), {
        status: 200,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );

  } catch (error: any) {
    console.error(`[Simulate] Error: ${error.message}`);

    // Update simulation status to failed
    try {
      if (simulationId) {
        const SUPABASE_URL = Deno.env.get('SUPABASE_URL');
        const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
        
        if (SUPABASE_URL && SUPABASE_SERVICE_ROLE_KEY) {
          const supabaseServiceRoleClient = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
          await supabaseServiceRoleClient
            .from('simulations')
            .update({ 
              status: 'failed', 
              progress: 0,
              error_message: error.message.substring(0, 500),
              completed_at: new Date().toISOString()
            })
            .eq('id', simulationId);
        }
      }
    } catch (updateError) {
      console.error(`[Simulate] Failed to update status: ${updateError.message}`);
    }

    return new Response(
      JSON.stringify({ 
        success: false, 
        error: error.message 
      }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );
  }
});
