// backend/supabase/functions/simulate/index.ts
import { createClient } from "npm:@supabase/supabase-js@2.38.0"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS, GET',
  'Access-Control-Allow-Credentials': 'true',
  'Vary': 'Origin'
}

const sleep = (ms: number) => new Promise((res) => setTimeout(res, ms))

// Fonction pour générer un maillage structuré simple (grille 3D)
function generateStructuredMesh(dimensions: [number, number, number], spacing: [number, number, number]) {
  const [nx, ny, nz] = dimensions;
  const [dx, dy, dz] = spacing;
  const points = [];
  const temperatureValues = [];
  
  for (let k = 0; k < nz; k++) {
    for (let j = 0; j < ny; j++) {
      for (let i = 0; i < nx; i++) {
        const x = i * dx;
        const y = j * dy;
        const z = k * dz;
        points.push(x, y, z);
        const center = [nx*dx/2, ny*dy/2, nz*dz/2];
        const distance = Math.sqrt(Math.pow(x - center[0], 2) + Math.pow(y - center[1], 2) + Math.pow(z - center[2], 2));
        const temperature = 25 + (175 * Math.exp(-distance / (Math.max(nx*dx, ny*dy, nz*dz) / 3)));
        temperatureValues.push(temperature);
      }
    }
  }
  return { points, temperatureValues };
}

function generateVTKFile(config: any, temperatureData: number[]) {
  const { dimensions, spacing } = config;
  const [nx, ny, nz] = dimensions;
  const [dx, dy, dz] = spacing;
  let vtkContent = `# vtk DataFile Version 4.2\nGenerated by Industrial Simulation\nASCII\nDATASET STRUCTURED_GRID\nDIMENSIONS ${nx} ${ny} ${nz}\nPOINTS ${nx * ny * nz} float\n`;
  for (let k = 0; k < nz; k++) {
    for (let j = 0; j < ny; j++) {
      for (let i = 0; i < nx; i++) {
        vtkContent += `${i * dx} ${j * dy} ${k * dz}\n`;
      }
    }
  }
  vtkContent += `\nPOINT_DATA ${nx * ny * nz}\nSCALARS temperature float 1\nLOOKUP_TABLE default\n`;
  for (const temp of temperatureData) vtkContent += `${temp}\n`;
  return vtkContent;
}

function formatResults(results: any, source: 'fastapi' | 'fallback') {
  return { ...results, source, timestamp: new Date().toISOString() };
}

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') return new Response(null, { status: 204, headers: corsHeaders });
  if (req.method !== 'POST') return new Response(JSON.stringify({ success: false, error: 'Method not allowed' }), { status: 405, headers: { ...corsHeaders, 'Content-Type': 'application/json' } });

  let simulationId: string | undefined = undefined;
  const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
  const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
  const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

  try {
    const authHeader = req.headers.get('Authorization');
    if (!authHeader?.startsWith('Bearer ')) throw new Error('Missing or invalid Authorization header');

    const body = await req.json();
    const { simulation_id: simId, config, user_id } = body;
    simulationId = simId;

    if (!simId || !config || !user_id) throw new Error('Missing required fields: simulation_id, config, user_id');

    console.log(`[Simulate] Starting simulation ${simId} for user ${user_id}`);

    // --- 1. TENTATIVE BACKEND FASTAPI ---
    const FASTAPI_URL = Deno.env.get('FASTAPI_URL') || 'https://voltflow-ai.onrender.com';
    let backendResults = null;
    
    try {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 25000); // 25s timeout for FastAPI

      const fastApiRes = await fetch(`${FASTAPI_URL}/api/v1/simulate/thermal`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          simulation_id: simId,
          geometry_file: config.geometry_config?.file_url || 'default.stl',
          material_id: config.material_id,
          boundary_conditions: {
            initial: config.boundary_conditions?.initial_temp || 25.0,
            boundary: config.boundary_conditions?.ambient_temp || 100.0,
          },
          mesh_density: config.mesh_density || 'medium',
        }),
        signal: controller.signal
      });
      clearTimeout(timeoutId);

      if (fastApiRes.ok) {
        const fastApiData = await fastApiRes.json();
        backendResults = formatResults(fastApiData.results, 'fastapi');
      }
    } catch (err) {
      console.warn(`[Simulate] Backend failed: ${err.message}. Using fallback...`);
    }

    // --- 2. FALLBACK ---
    let finalResults;
    if (backendResults) {
      finalResults = backendResults;
    } else {
      const meshDensity = config.mesh_density || 'medium';
      let dimensions: [number, number, number] = [30, 30, 30], spacing: [number, number, number] = [3.33, 3.33, 3.33];
      if (meshDensity === 'low') { dimensions = [20, 20, 20]; spacing = [5, 5, 5]; }
      else if (meshDensity === 'high') { dimensions = [50, 50, 50]; spacing = [2, 2, 2]; }

      const { points, temperatureValues } = generateStructuredMesh(dimensions, spacing);
      const vtkContent = generateVTKFile({ dimensions, spacing }, temperatureValues);
      const fileName = `simulation_${simId}_${Date.now()}.vtk`;
      const filePath = `${user_id}/${fileName}`;

      const { error: uploadError } = await supabase.storage.from('simulation-files').upload(filePath, vtkContent, { contentType: 'text/plain' });
      if (uploadError) throw new Error(`Failed to upload VTK: ${uploadError.message}`);

      const { data: urlData } = supabase.storage.from('simulation-files').getPublicUrl(filePath);

      finalResults = formatResults({
        vtk_file_url: urlData.publicUrl,
        max_temperature: Math.max(...temperatureValues),
        min_temperature: Math.min(...temperatureValues),
        average_temperature: temperatureValues.reduce((a, b) => a + b, 0) / temperatureValues.length,
        computation_time: dimensions[0] * dimensions[1] * dimensions[2] * 0.01,
        uncertainty_score: Math.random() * 0.15,
        convergence_rate: 0.95 + Math.random() * 0.04,
        temperature_field: { values: temperatureValues, units: '°C', resolution: dimensions },
        mesh_points: dimensions[0] * dimensions[1] * dimensions[2],
      }, 'fallback');
    }

    // --- 3. PERSISTENCE ---
    await supabase.from('simulation_results').insert({
      simulation_id: simId,
      temperature_data: finalResults.temperature_field,
      max_temperature: finalResults.max_temperature,
      min_temperature: finalResults.min_temperature,
      uncertainty_score: finalResults.uncertainty_score,
      result_files: { vtk_url: finalResults.vtk_file_url, source: finalResults.source }
    });

    await supabase.from('simulations').update({
      status: 'completed',
      progress: 100,
      completed_at: new Date().toISOString()
    }).eq('id', simId);

    return new Response(JSON.stringify({ success: true, results: finalResults }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });

  } catch (error: any) {
    console.error(`[CRITICAL] ${error.message}`);
    if (simulationId) {
      await supabase.from('simulations').update({
        status: 'failed',
        error_message: error.message,
        completed_at: new Date().toISOString()
      }).eq('id', simulationId);
    }
    return new Response(JSON.stringify({ success: false, error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
  }
});
